//! The catalog of configuration files the Config tab may show and edit.
//!
//! Two roots: the engine's etc dir (`/etc/MailScanner` or ConfigServer's
//! `/usr/mailscanner/etc`) and the directory of MSFE-NG's own `config.toml`.
//! `scan` walks them and classifies every file by its relative path — what
//! kind of editor it gets, what MailScanner needs after a change (a restart
//! for files it reads at start, a reload for rulesets it re-reads per batch)
//! and how a candidate is validated. A request may only name a file by the id
//! the scan produced, so nothing outside the two trees is ever reachable.

use crate::{rules, service, Config};
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Root {
    /// The MailScanner etc dir — ids `ms:<rel>`.
    Ms,
    /// `/etc/msfe-ng` — ids `msfe:<rel>`.
    Msfe,
}

impl Root {
    pub fn prefix(&self) -> &'static str {
        match self {
            Root::Ms => "ms",
            Root::Msfe => "msfe",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReadOnlyReason {
    /// Regenerated by `msfe-ng sync` from the policy (edit it on the Rules tab).
    GeneratedBySync,
    /// Rewritten by ms-update-phishing (edit the `.custom` list instead).
    GeneratedByPhishingUpdater,
    /// Code shipped by MSFE-NG or MailScanner, replaced on upgrade.
    ShippedCode,
    /// The engine's run options latch (`defaults`), owned by the installer.
    Defaults,
    /// A package manager's `.rpmnew` / `.rpmsave` copy.
    Vendor,
}

impl ReadOnlyReason {
    pub fn as_str(&self) -> &'static str {
        match self {
            ReadOnlyReason::GeneratedBySync => "generated by sync — edit on the Rules tab",
            ReadOnlyReason::GeneratedByPhishingUpdater => {
                "rewritten by ms-update-phishing — edit the .custom list"
            }
            ReadOnlyReason::ShippedCode => "shipped code, replaced on upgrade",
            ReadOnlyReason::Defaults => "engine run options, managed by the installer",
            ReadOnlyReason::Vendor => "package manager copy",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Kind {
    KeyValue(crate::conffile::Style),
    RuleTable,
    FilenameRules,
    SpamLists,
    VirusScanners,
    HostList,
    PlainText,
    ReadOnly(ReadOnlyReason),
}

impl Kind {
    pub fn as_str(&self) -> &'static str {
        match self {
            Kind::KeyValue(crate::conffile::Style::Plain) => "keyvalue",
            Kind::KeyValue(crate::conffile::Style::Toml) => "toml",
            Kind::RuleTable => "rules",
            Kind::FilenameRules => "filename-rules",
            Kind::SpamLists => "spam-lists",
            Kind::VirusScanners => "virus-scanners",
            Kind::HostList => "host-list",
            Kind::PlainText => "text",
            Kind::ReadOnly(_) => "readonly",
        }
    }
    pub fn editable(&self) -> bool {
        !matches!(self, Kind::ReadOnly(_))
    }
}

/// What MailScanner needs after the file changed.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reload {
    /// Read at start only (MailScanner.conf, spamassassin.conf, …).
    Restart,
    /// Re-read per batch (rulesets, filename rules, phishing lists).
    Reload,
    None,
}

impl Reload {
    pub fn as_str(&self) -> &'static str {
        match self {
            Reload::Restart => "restart",
            Reload::Reload => "reload",
            Reload::None => "none",
        }
    }
}

/// How a candidate is validated before it goes live.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Validator {
    /// `MailScanner --lint <staged conf>` on a staged copy of the etc tree.
    MsLint,
    /// `MailScanner --lint` after the file is applied, rolled back on failure
    /// — for `conf.d` fragments, which the engine reads from the live dir
    /// whatever conf path it is given.
    MsLintAfter,
    /// `spamassassin --lint -p <staged prefs>`.
    SaLint,
    /// The kind's own parser only.
    Syntax,
    /// `Config::from_toml_str` round-trip.
    TomlLoad,
}

impl Validator {
    pub fn as_str(&self) -> &'static str {
        match self {
            Validator::MsLint => "mailscanner-lint",
            Validator::MsLintAfter => "mailscanner-lint-after",
            Validator::SaLint => "spamassassin-lint",
            Validator::Syntax => "syntax",
            Validator::TomlLoad => "toml",
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct Entry {
    /// `ms:rules/bounce.rules`, `msfe:config.toml`.
    pub id: String,
    pub root: Root,
    pub rel: String,
    pub path: PathBuf,
    pub kind: Kind,
    pub reload: Reload,
    pub validator: Validator,
    pub size: u64,
    pub mtime: u64,
    /// Where the containing directory points when it is a symlink (`reports`).
    pub symlink_target: Option<PathBuf>,
}

#[derive(Debug, Clone)]
pub struct Catalog {
    pub ms_etc: PathBuf,
    pub msfe_dir: PathBuf,
    pub entries: Vec<Entry>,
}

/// Subdirectories of the etc dir that are walked (one level).
const MS_SUBDIRS: [&str; 5] = ["conf.d", "mcp", "rules", "custom", "reports"];

fn etc_of(cfg: &Config) -> PathBuf {
    Path::new(&cfg.mailscanner_conf)
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_else(|| "/etc/MailScanner".into())
}

/// Classify a file by its path relative to the root. Pure: the same answer
/// for the same name on every host.
pub fn classify(root: Root, rel: &str) -> (Kind, Reload, Validator) {
    use crate::conffile::Style;
    let name = rel.rsplit('/').next().unwrap_or(rel);
    if name.ends_with(".rpmnew") || name.ends_with(".rpmsave") {
        return (
            Kind::ReadOnly(ReadOnlyReason::Vendor),
            Reload::None,
            Validator::Syntax,
        );
    }
    match root {
        Root::Msfe => match rel {
            "config.toml" => (
                Kind::KeyValue(Style::Toml),
                Reload::None,
                Validator::TomlLoad,
            ),
            _ => (Kind::PlainText, Reload::None, Validator::Syntax),
        },
        Root::Ms => {
            let (dir, base) = match rel.split_once('/') {
                Some((d, b)) => (d, b),
                None => ("", rel),
            };
            match dir {
                "" => match base {
                    "MailScanner.conf" => (
                        Kind::KeyValue(Style::Plain),
                        Reload::Restart,
                        Validator::MsLint,
                    ),
                    "spamassassin.conf" => (Kind::PlainText, Reload::Restart, Validator::SaLint),
                    "spam.lists.conf" => (Kind::SpamLists, Reload::Restart, Validator::MsLint),
                    "virus.scanners.conf" => {
                        (Kind::VirusScanners, Reload::Restart, Validator::MsLint)
                    }
                    "country.domains.conf" => (Kind::PlainText, Reload::Reload, Validator::Syntax),
                    "defaults" => (
                        Kind::ReadOnly(ReadOnlyReason::Defaults),
                        Reload::None,
                        Validator::Syntax,
                    ),
                    _ if base.ends_with(".rules.conf") => {
                        (Kind::FilenameRules, Reload::Reload, Validator::MsLint)
                    }
                    _ if base.starts_with("phishing.") && base.ends_with(".custom") => {
                        (Kind::HostList, Reload::Reload, Validator::Syntax)
                    }
                    _ if base.starts_with("phishing.") => (
                        Kind::ReadOnly(ReadOnlyReason::GeneratedByPhishingUpdater),
                        Reload::None,
                        Validator::Syntax,
                    ),
                    _ => (Kind::PlainText, Reload::Restart, Validator::Syntax),
                },
                "conf.d" => {
                    if base.ends_with(".conf") {
                        (
                            Kind::KeyValue(Style::Plain),
                            Reload::Restart,
                            Validator::MsLintAfter,
                        )
                    } else {
                        (Kind::PlainText, Reload::None, Validator::Syntax)
                    }
                }
                "mcp" => {
                    if base == "mcp.spamassassin.conf" {
                        (Kind::PlainText, Reload::Restart, Validator::SaLint)
                    } else {
                        (Kind::PlainText, Reload::Restart, Validator::Syntax)
                    }
                }
                "rules" => {
                    if base.ends_with(".rules") {
                        if rules::managed_files().iter().any(|m| m == base) {
                            (
                                Kind::ReadOnly(ReadOnlyReason::GeneratedBySync),
                                Reload::None,
                                Validator::Syntax,
                            )
                        } else {
                            (Kind::RuleTable, Reload::Reload, Validator::MsLint)
                        }
                    } else {
                        (Kind::PlainText, Reload::None, Validator::Syntax)
                    }
                }
                "custom" => (
                    Kind::ReadOnly(ReadOnlyReason::ShippedCode),
                    Reload::None,
                    Validator::Syntax,
                ),
                "reports" => (Kind::PlainText, Reload::None, Validator::Syntax),
                _ => (Kind::PlainText, Reload::None, Validator::Syntax),
            }
        }
    }
}

/// Names never shown: our own temp/backup files, dotfiles, compressed data.
fn skip(name: &str) -> bool {
    name.starts_with('.')
        || name.ends_with(".tmp.msfe-ng")
        || name.ends_with(".msfe-ng.bak")
        || name.ends_with(".gz")
}

fn entry(root: Root, root_dir: &Path, rel: &str, symlink_target: Option<PathBuf>) -> Option<Entry> {
    let path = root_dir.join(rel);
    let meta = std::fs::metadata(&path).ok()?;
    if !meta.is_file() {
        return None;
    }
    use std::os::unix::fs::MetadataExt;
    let (kind, reload, validator) = classify(root, rel);
    Some(Entry {
        id: format!("{}:{rel}", root.prefix()),
        root,
        rel: rel.to_string(),
        path,
        kind,
        reload,
        validator,
        size: meta.len(),
        mtime: meta.mtime().max(0) as u64,
        symlink_target,
    })
}

fn sorted_names(dir: &Path) -> Vec<String> {
    let mut names: Vec<String> = std::fs::read_dir(dir)
        .map(|rd| {
            rd.filter_map(Result::ok)
                .filter_map(|e| e.file_name().to_str().map(str::to_string))
                .filter(|n| !skip(n))
                .collect()
        })
        .unwrap_or_default();
    names.sort();
    names
}

/// Walk both roots. Files at the root level plus one level of the known
/// subdirectories (`reports/` two levels: a language dir per template set).
pub fn scan(cfg: &Config, config_file: &Path) -> Catalog {
    let ms_etc = etc_of(cfg);
    let msfe_dir = config_file
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_else(|| "/etc/msfe-ng".into());
    let mut entries = Vec::new();

    for name in sorted_names(&ms_etc) {
        if let Some(e) = entry(Root::Ms, &ms_etc, &name, None) {
            entries.push(e);
        }
    }
    for sub in MS_SUBDIRS {
        let dir = ms_etc.join(sub);
        if !dir.is_dir() {
            continue;
        }
        let target = std::fs::read_link(&dir).ok();
        if sub == "reports" {
            for lang in sorted_names(&dir) {
                let ldir = dir.join(&lang);
                if !ldir.is_dir() {
                    continue;
                }
                for name in sorted_names(&ldir) {
                    let rel = format!("{sub}/{lang}/{name}");
                    if let Some(e) = entry(Root::Ms, &ms_etc, &rel, target.clone()) {
                        entries.push(e);
                    }
                }
            }
            continue;
        }
        for name in sorted_names(&dir) {
            let rel = format!("{sub}/{name}");
            if let Some(e) = entry(Root::Ms, &ms_etc, &rel, target.clone()) {
                entries.push(e);
            }
        }
    }

    if let Some(e) = entry(
        Root::Msfe,
        &msfe_dir,
        config_file
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("config.toml"),
        None,
    ) {
        entries.push(e);
    }

    Catalog {
        ms_etc,
        msfe_dir,
        entries,
    }
}

/// Files MailScanner reads at start that changed after the service last
/// started: a restart is pending. `since` is the service's start time (epoch
/// seconds); `None` (not running / unknown) means nothing is pending.
pub fn pending_restart(entries: &[Entry], since: Option<u64>) -> Vec<String> {
    let Some(since) = since else {
        return Vec::new();
    };
    entries
        .iter()
        .filter(|e| e.reload == Reload::Restart && e.mtime > since)
        .map(|e| e.id.clone())
        .collect()
}

/// The entry for `id`, only when the scan produces it — the sole way a
/// request may address a file.
pub fn resolve(cfg: &Config, config_file: &Path, id: &str) -> Option<Entry> {
    if id.contains("..") || id.contains('\0') {
        return None;
    }
    scan(cfg, config_file)
        .entries
        .into_iter()
        .find(|e| e.id == id)
}

/// A file the editor may create: `conf.d/<name>.conf` or `rules/<name>.rules`,
/// the name passing `service::safe_name`. Returns its future classification.
pub fn creatable(dir: &str, name: &str) -> Option<(Kind, Reload, Validator)> {
    if !service::safe_name(name) {
        return None;
    }
    let ok = match dir {
        "conf.d" => name.ends_with(".conf") && name.len() > 5,
        "rules" => name.ends_with(".rules") && name.len() > 6,
        _ => false,
    };
    if !ok {
        return None;
    }
    let (kind, reload, validator) = classify(Root::Ms, &format!("{dir}/{name}"));
    kind.editable().then_some((kind, reload, validator))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::conffile::Style;

    fn tree(tag: &str) -> (PathBuf, Config, PathBuf) {
        let base = std::env::temp_dir().join(format!("msfe-catalog-{tag}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&base);
        let etc = base.join("etc/MailScanner");
        for d in ["conf.d", "mcp", "rules", "custom", "reports-target/en"] {
            std::fs::create_dir_all(etc.join(d)).unwrap();
        }
        let w = |rel: &str, body: &str| std::fs::write(etc.join(rel), body).unwrap();
        w("MailScanner.conf", "%etc-dir% = /x\nMax Children = 5\n");
        w("MailScanner.conf.msfe-ng.bak", "old");
        w("MailScanner.conf.tmp.msfe-ng", "tmp");
        w("spamassassin.conf", "score X 1\n");
        w("spamassassin.conf.rpmnew", "score X 2\n");
        w("spam.lists.conf", "SPAMCOP bl.spamcop.net.\n");
        w("virus.scanners.conf", "clamd /bin/false /usr\n");
        w("filename.rules.conf", "deny\t\\.exe$\ta\tb\n");
        w("archives.filetype.rules.conf", "allow\ttext\t-\t-\n");
        w("phishing.bad.sites.custom", "bad.example\n");
        w("phishing.bad.sites.conf", "bad.example\n");
        w("phishing.safe.sites.conf.master", "x\n");
        w("country.domains.conf", "co.uk\n");
        w("defaults", "run_mailscanner=1\n");
        w(".hidden", "no");
        w("conf.d/README", "readme");
        w("conf.d/10-local.conf", "Max Children = 7\n");
        w("mcp/mcp.spamassassin.conf", "use_bayes 0\n");
        w("mcp/10_example.cf", "body X /x/\n");
        w("rules/spam.whitelist.rules", "From: default no\n");
        w("rules/bounce.rules", "FromOrTo: default no\n");
        w("rules/README", "r");
        w("custom/MSFENG.pm", "package X;\n");
        w("reports-target/en/deleted.virus.message.txt", "gone\n");
        std::os::unix::fs::symlink(etc.join("reports-target"), etc.join("reports")).unwrap();
        let msfe = base.join("etc/msfe-ng");
        std::fs::create_dir_all(&msfe).unwrap();
        std::fs::write(msfe.join("config.toml"), "panel = \"x\"\n").unwrap();
        let cfg = Config {
            mailscanner_conf: etc.join("MailScanner.conf").display().to_string(),
            ..Config::default()
        };
        (base, cfg, msfe.join("config.toml"))
    }

    fn kinds(cat: &Catalog) -> Vec<(String, Kind, Reload, Validator)> {
        cat.entries
            .iter()
            .map(|e| (e.id.clone(), e.kind, e.reload, e.validator))
            .collect()
    }

    #[test]
    fn scan_classifies_every_kind_and_skips_noise() {
        let (base, cfg, conf) = tree("scan");
        let cat = scan(&cfg, &conf);
        let k = kinds(&cat);
        let find = |id: &str| {
            k.iter()
                .find(|x| x.0 == id)
                .unwrap_or_else(|| panic!("{id} missing"))
                .clone()
        };
        assert_eq!(find("ms:MailScanner.conf").1, Kind::KeyValue(Style::Plain));
        assert_eq!(find("ms:MailScanner.conf").2, Reload::Restart);
        assert_eq!(find("ms:MailScanner.conf").3, Validator::MsLint);
        assert_eq!(find("ms:spamassassin.conf").1, Kind::PlainText);
        assert_eq!(find("ms:spamassassin.conf").3, Validator::SaLint);
        assert_eq!(
            find("ms:spamassassin.conf.rpmnew").1,
            Kind::ReadOnly(ReadOnlyReason::Vendor)
        );
        assert_eq!(find("ms:spam.lists.conf").1, Kind::SpamLists);
        assert_eq!(find("ms:virus.scanners.conf").1, Kind::VirusScanners);
        assert_eq!(find("ms:filename.rules.conf").1, Kind::FilenameRules);
        assert_eq!(find("ms:filename.rules.conf").2, Reload::Reload);
        assert_eq!(
            find("ms:archives.filetype.rules.conf").1,
            Kind::FilenameRules
        );
        assert_eq!(find("ms:phishing.bad.sites.custom").1, Kind::HostList);
        assert_eq!(
            find("ms:phishing.bad.sites.conf").1,
            Kind::ReadOnly(ReadOnlyReason::GeneratedByPhishingUpdater)
        );
        assert_eq!(
            find("ms:phishing.safe.sites.conf.master").1,
            Kind::ReadOnly(ReadOnlyReason::GeneratedByPhishingUpdater)
        );
        assert_eq!(find("ms:country.domains.conf").1, Kind::PlainText);
        assert_eq!(
            find("ms:defaults").1,
            Kind::ReadOnly(ReadOnlyReason::Defaults)
        );
        assert_eq!(
            find("ms:conf.d/10-local.conf").1,
            Kind::KeyValue(Style::Plain)
        );
        assert_eq!(find("ms:conf.d/10-local.conf").3, Validator::MsLintAfter);
        assert_eq!(find("ms:conf.d/README").1, Kind::PlainText);
        assert_eq!(find("ms:mcp/mcp.spamassassin.conf").3, Validator::SaLint);
        assert_eq!(find("ms:mcp/10_example.cf").3, Validator::Syntax);
        assert_eq!(
            find("ms:rules/spam.whitelist.rules").1,
            Kind::ReadOnly(ReadOnlyReason::GeneratedBySync)
        );
        assert_eq!(find("ms:rules/bounce.rules").1, Kind::RuleTable);
        assert_eq!(find("ms:rules/bounce.rules").2, Reload::Reload);
        assert_eq!(find("ms:rules/README").1, Kind::PlainText);
        assert_eq!(
            find("ms:custom/MSFENG.pm").1,
            Kind::ReadOnly(ReadOnlyReason::ShippedCode)
        );
        assert_eq!(
            find("ms:reports/en/deleted.virus.message.txt").1,
            Kind::PlainText
        );
        assert_eq!(
            find("ms:reports/en/deleted.virus.message.txt").2,
            Reload::None
        );
        assert_eq!(find("msfe:config.toml").1, Kind::KeyValue(Style::Toml));
        assert_eq!(find("msfe:config.toml").3, Validator::TomlLoad);
        // noise never listed
        for id in [
            "ms:MailScanner.conf.msfe-ng.bak",
            "ms:MailScanner.conf.tmp.msfe-ng",
            "ms:.hidden",
        ] {
            assert!(!k.iter().any(|x| x.0 == id), "{id} listed");
        }
        // the reports symlink is followed and its target recorded
        let rep = cat
            .entries
            .iter()
            .find(|e| e.rel.starts_with("reports/"))
            .unwrap();
        assert_eq!(
            rep.symlink_target.as_deref(),
            Some(base.join("etc/MailScanner/reports-target").as_path())
        );
        assert!(rep.size > 0 && rep.mtime > 0);
        let _ = std::fs::remove_dir_all(&base);
    }

    #[test]
    fn resolve_only_answers_scanned_ids() {
        let (base, cfg, conf) = tree("resolve");
        let e = resolve(&cfg, &conf, "ms:rules/bounce.rules").unwrap();
        assert_eq!(e.path, base.join("etc/MailScanner/rules/bounce.rules"));
        assert!(resolve(&cfg, &conf, "ms:../msfe-ng/config.toml").is_none());
        assert!(resolve(&cfg, &conf, "ms:rules/../MailScanner.conf").is_none());
        assert!(resolve(&cfg, &conf, "ms:nonexistent").is_none());
        assert!(resolve(&cfg, &conf, "msfe:config.toml").is_some());
        assert!(resolve(&cfg, &conf, "ms:MailScanner.conf.msfe-ng.bak").is_none());
        let _ = std::fs::remove_dir_all(&base);
    }

    #[test]
    fn creatable_names() {
        assert_eq!(
            creatable("conf.d", "20-site.conf"),
            Some((
                Kind::KeyValue(Style::Plain),
                Reload::Restart,
                Validator::MsLintAfter
            ))
        );
        assert_eq!(
            creatable("rules", "my.rules"),
            Some((Kind::RuleTable, Reload::Reload, Validator::MsLint))
        );
        assert!(creatable("rules", "spam.whitelist.rules").is_none()); // managed → read-only
        assert!(creatable("rules", "x.conf").is_none());
        assert!(creatable("conf.d", ".conf").is_none());
        assert!(creatable("conf.d", "../x.conf").is_none());
        assert!(creatable("mcp", "x.cf").is_none());
    }

    #[test]
    fn pending_restart_names_start_only_files_newer_than_the_service() {
        let (base, cfg, conf) = tree("pending");
        let cat = scan(&cfg, &conf);
        let now = cat.entries[0].mtime;
        assert!(pending_restart(&cat.entries, None).is_empty());
        assert!(pending_restart(&cat.entries, Some(now + 10)).is_empty());
        let p = pending_restart(&cat.entries, Some(now - 10));
        assert!(p.contains(&"ms:MailScanner.conf".to_string()));
        assert!(p.contains(&"ms:spamassassin.conf".to_string()));
        assert!(
            !p.contains(&"ms:rules/bounce.rules".to_string()),
            "rulesets reload per batch"
        );
        assert!(!p.contains(&"msfe:config.toml".to_string()));
        let _ = std::fs::remove_dir_all(&base);
    }

    #[test]
    fn classify_is_pure_and_defensive() {
        assert_eq!(classify(Root::Ms, "whatever.txt").0, Kind::PlainText);
        assert_eq!(classify(Root::Ms, "deep/er/file").0, Kind::PlainText);
        assert_eq!(classify(Root::Msfe, "policy.txt").0, Kind::PlainText);
        assert_eq!(
            classify(Root::Ms, "rules/x.rules.rpmnew").0,
            Kind::ReadOnly(ReadOnlyReason::Vendor)
        );
    }
}

// ---- search ---------------------------------------------------------------------

/// One line of one configuration file that contains the query.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Hit {
    pub id: String,
    pub rel: String,
    /// 1-based.
    pub line: usize,
    pub text: String,
}

/// Every line of every catalogued file containing `query`, case-insensitive,
/// in catalog order, at most `limit` hits. Binary-looking files (a NUL in
/// the first block) are skipped.
pub fn search(cat: &Catalog, query: &str, limit: usize) -> Vec<Hit> {
    let q = query.trim().to_lowercase();
    if q.is_empty() {
        return Vec::new();
    }
    let mut out = Vec::new();
    for e in &cat.entries {
        let Ok(bytes) = std::fs::read(&e.path) else {
            continue;
        };
        if bytes.iter().take(4096).any(|&b| b == 0) {
            continue;
        }
        let text = String::from_utf8_lossy(&bytes);
        for (i, line) in text.lines().enumerate() {
            if line.to_lowercase().contains(&q) {
                out.push(Hit {
                    id: e.id.clone(),
                    rel: e.rel.clone(),
                    line: i + 1,
                    text: line.trim_end().chars().take(300).collect(),
                });
                if out.len() >= limit {
                    return out;
                }
            }
        }
    }
    out
}

#[cfg(test)]
mod search_tests {
    use super::*;

    #[test]
    fn search_finds_lines_case_insensitively_across_the_catalog() {
        let base = std::env::temp_dir().join(format!("msfe-confsearch-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&base);
        let etc = base.join("etc/MailScanner");
        std::fs::create_dir_all(etc.join("rules")).unwrap();
        std::fs::create_dir_all(base.join("etc/msfe-ng")).unwrap();
        std::fs::write(
            etc.join("MailScanner.conf"),
            "%org-name% = acme\nMax Spam Check Size = 2M\nFilename Rules = %etc-dir%/filename.rules.conf\n",
        )
        .unwrap();
        std::fs::write(
            etc.join("filename.rules.conf"),
            "deny\t\\.exe$\tprog\tprog\nallow\t\\.eml$\t-\t-\n",
        )
        .unwrap();
        std::fs::write(etc.join("rules/spam.rules"), "FromOrTo: default yes\n").unwrap();
        std::fs::write(base.join("etc/msfe-ng/config.toml"), "panel = \"cpanel\"\n").unwrap();
        let cfg = Config {
            mailscanner_conf: etc.join("MailScanner.conf").display().to_string(),
            mailscanner_rules_dir: etc.join("rules").display().to_string(),
            ..Config::default()
        };
        let cat = scan(&cfg, &base.join("etc/msfe-ng/config.toml"));
        let hits = search(&cat, "EML", 100);
        assert_eq!(hits.len(), 1, "{hits:?}");
        assert_eq!(hits[0].rel, "filename.rules.conf");
        assert_eq!(hits[0].line, 2);
        assert!(hits[0].text.starts_with("allow"));
        let hits = search(&cat, "filename", 100);
        assert!(
            hits.iter()
                .any(|h| h.rel == "MailScanner.conf" && h.line == 3),
            "{hits:?}"
        );
        assert_eq!(search(&cat, "filename", 1).len(), 1, "limit");
        assert!(search(&cat, "   ", 100).is_empty());
        let _ = std::fs::remove_dir_all(&base);
    }
}
