//! The diagnostic inbox: a one-time address `dt-<token>@<hostname>` that
//! anyone can send a message to; Exim delivers it into a maildir this
//! daemon owns, and the report says what the sender's mail looks like on
//! arrival (authentication as our Exim saw it, TLS in, MailScanner's score,
//! the message's own shape). Wired through `/etc/exim.conf.local` with two
//! `.include_if_exists` lines — deleting the fragment files switches it off.

use crate::config::Config;
use crate::delivery::{Category, Check, Fix, Scope, Severity, Verdict};
use crate::json::Json;
use std::path::PathBuf;

pub const START_MARKER: &str = "# --- MSFE-NG diagnostic inbox start ---";
pub const END_MARKER: &str = "# --- MSFE-NG diagnostic inbox end ---";
/// How long a token accepts mail.
pub const TTL_SECS: u64 = 30 * 60;
/// Received messages and expired boxes are removed after this.
const BOX_KEEP_SECS: u64 = 24 * 3600;
const MAX_MESSAGE_BYTES: u64 = 10 * 1024 * 1024;

pub fn exim_conf_local() -> PathBuf {
    std::env::var("MSFE_NG_EXIM_CONF_LOCAL")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from("/etc/exim.conf.local"))
}

pub fn conf_dir() -> PathBuf {
    std::env::var("MSFE_NG_DIAG_CONF_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from("/etc/msfe-ng"))
}

pub fn spool_dir() -> PathBuf {
    std::env::var("MSFE_NG_DIAG_SPOOL")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from("/var/spool/msfe-ng/diag"))
}

fn router_path() -> PathBuf {
    conf_dir().join("diag-router.conf")
}

fn transport_path() -> PathBuf {
    conf_dir().join("diag-transport.conf")
}

/// The host name the inbox addresses use.
pub fn hostname(cfg: &Config) -> String {
    if let Ok(h) = std::env::var("MSFE_NG_DIAG_HOSTNAME") {
        return h;
    }
    if !cfg.delivery_helo.trim().is_empty() {
        return cfg.delivery_helo.trim().to_string();
    }
    std::process::Command::new("hostname")
        .arg("-f")
        .output()
        .ok()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .filter(|s| s.contains('.'))
        .unwrap_or_else(|| "localhost".into())
}

pub fn router_fragment() -> String {
    let spool = spool_dir();
    format!(
        "{START_MARKER}
# Accepts mail for dt-<token>@<this host> while active/dt-<token> exists and
# hands it to the daemon-owned maildir box/dt-<token>. Generated by `msfe-ng delivery
# inbox install`; remove this file to switch the inbox off.
# (dsearch de-taints the local part: only a name that exists in the active
# directory ever reaches the transport's directory setting)
msfe_ng_diag:
  driver = accept
  domains = $primary_hostname
  local_parts = \\N^dt-[a-z0-9]{{16}}$\\N
  condition = ${{lookup {{$local_part}} dsearch{{{active}}} {{yes}}{{no}}}}
  transport = msfe_ng_diag_delivery
  no_more
{END_MARKER}
",
        active = spool.join("active").display()
    )
}

pub fn transport_fragment() -> String {
    let spool = spool_dir();
    format!(
        "{START_MARKER}
msfe_ng_diag_delivery:
  driver = appendfile
  maildir_format
  directory = {boxes}/${{lookup {{$local_part}} dsearch{{{active}}}}}
  create_directory
  directory_mode = 0700
  mode = 0600
  user = mailnull
  group = mail
  quota = 10M
{END_MARKER}
",
        boxes = spool.join("box").display(),
        active = spool.join("active").display()
    )
}

fn include_lines() -> (String, String) {
    (
        format!(".include_if_exists {}", router_path().display()),
        format!(".include_if_exists {}", transport_path().display()),
    )
}

/// `exim.conf.local` with our include lines placed under `@PREROUTERS@` and
/// `@TRANSPORTSTART@` (between markers), or removed. Missing section
/// markers are added at the end. Returns the new text and whether it changed.
pub fn splice(text: &str, install: bool) -> (String, bool) {
    // strip an earlier block of ours everywhere
    let mut lines: Vec<String> = Vec::new();
    let mut skipping = false;
    for l in text.lines() {
        if l.trim() == START_MARKER {
            skipping = true;
            continue;
        }
        if l.trim() == END_MARKER {
            skipping = false;
            continue;
        }
        if !skipping {
            lines.push(l.to_string());
        }
    }
    if install {
        let (r, t) = include_lines();
        for (marker, line) in [("@PREROUTERS@", r), ("@TRANSPORTSTART@", t)] {
            let block = [START_MARKER.to_string(), line, END_MARKER.to_string()];
            match lines.iter().position(|l| l.trim() == marker) {
                Some(i) => {
                    for (k, b) in block.iter().enumerate() {
                        lines.insert(i + 1 + k, b.clone());
                    }
                }
                None => {
                    if lines.last().is_some_and(|l| !l.trim().is_empty()) {
                        lines.push(String::new());
                    }
                    lines.push(marker.to_string());
                    lines.extend(block.iter().cloned());
                }
            }
        }
    }
    let mut out = lines.join("\n");
    out.push('\n');
    (out.clone(), out != text && !(text.is_empty() && !install))
}

#[derive(Debug, Default)]
pub struct WireReport {
    pub actions: Vec<String>,
    pub dry_run: bool,
}

fn exim_rebuild(actions: &mut Vec<String>, dry: bool) {
    for cmd in ["/scripts/buildeximconf", "/scripts/restartsrv_exim"] {
        if dry || std::env::var("MSFE_NG_SKIP_EXIM_CMDS").is_ok() {
            actions.push(format!("would run: {cmd}"));
            continue;
        }
        let ok = std::process::Command::new(cmd)
            .status()
            .map(|s| s.success())
            .unwrap_or(false);
        actions.push(format!("ran {cmd}: {}", if ok { "ok" } else { "FAILED" }));
    }
}

fn ensure_dirs(actions: &mut Vec<String>, dry: bool) -> std::io::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    let spool = spool_dir();
    for (dir, mode) in [
        (spool.clone(), 0o755),
        (spool.join("active"), 0o755),
        (spool.join("box"), 0o770),
    ] {
        if dry {
            actions.push(format!("would create {} ({mode:o})", dir.display()));
            continue;
        }
        std::fs::create_dir_all(&dir)?;
        std::fs::set_permissions(&dir, std::fs::Permissions::from_mode(mode))?;
        actions.push(format!("directory {} ({mode:o})", dir.display()));
    }
    if !dry {
        // the box directory belongs to Exim's delivery user
        if let Some(uid) = user_id("mailnull") {
            let gid = group_id("mail").unwrap_or(uid);
            let _ = std::process::Command::new("chown")
                .arg(format!("{uid}:{gid}"))
                .arg(spool.join("box"))
                .status();
        }
    }
    Ok(())
}

fn user_id(name: &str) -> Option<u32> {
    std::fs::read_to_string("/etc/passwd")
        .ok()?
        .lines()
        .find_map(|l| {
            let f: Vec<&str> = l.split(':').collect();
            (f.len() > 2 && f[0] == name)
                .then(|| f[2].parse().ok())
                .flatten()
        })
}

fn group_id(name: &str) -> Option<u32> {
    std::fs::read_to_string("/etc/group")
        .ok()?
        .lines()
        .find_map(|l| {
            let f: Vec<&str> = l.split(':').collect();
            (f.len() > 2 && f[0] == name)
                .then(|| f[2].parse().ok())
                .flatten()
        })
}

/// Install the router/transport fragments and the include lines. Idempotent.
pub fn wire(cfg: &Config, dry: bool) -> std::io::Result<WireReport> {
    if cfg.panel != "cpanel" && std::env::var("MSFE_NG_EXIM_CONF_LOCAL").is_err() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::Unsupported,
            "the diagnostic inbox is implemented for cPanel's Exim (exim.conf.local) only",
        ));
    }
    let mut actions = Vec::new();
    ensure_dirs(&mut actions, dry)?;
    for (path, text) in [
        (router_path(), router_fragment()),
        (transport_path(), transport_fragment()),
    ] {
        if dry {
            actions.push(format!("would write {}", path.display()));
        } else {
            if let Some(d) = path.parent() {
                std::fs::create_dir_all(d)?;
            }
            crate::sync::atomic_write(&path, text.as_bytes())?;
            actions.push(format!("wrote {}", path.display()));
        }
    }
    let local = exim_conf_local();
    let cur = std::fs::read_to_string(&local).unwrap_or_default();
    let (new, changed) = splice(&cur, true);
    if changed {
        if dry {
            actions.push(format!(
                "would add the include lines to {}",
                local.display()
            ));
        } else {
            crate::sync::atomic_write(&local, new.as_bytes())?;
            actions.push(format!("added the include lines to {}", local.display()));
        }
    } else {
        actions.push(format!("{} already has the include lines", local.display()));
    }
    exim_rebuild(&mut actions, dry);
    Ok(WireReport {
        actions,
        dry_run: dry,
    })
}

/// Remove the include lines and the fragments. Idempotent.
pub fn unwire(dry: bool) -> std::io::Result<WireReport> {
    let mut actions = Vec::new();
    let local = exim_conf_local();
    if let Ok(cur) = std::fs::read_to_string(&local) {
        let (new, changed) = splice(&cur, false);
        if changed {
            if dry {
                actions.push(format!(
                    "would remove the include lines from {}",
                    local.display()
                ));
            } else {
                crate::sync::atomic_write(&local, new.as_bytes())?;
                actions.push(format!(
                    "removed the include lines from {}",
                    local.display()
                ));
            }
        }
    }
    for path in [router_path(), transport_path()] {
        if path.exists() {
            if dry {
                actions.push(format!("would remove {}", path.display()));
            } else {
                std::fs::remove_file(&path)?;
                actions.push(format!("removed {}", path.display()));
            }
        }
    }
    if actions.is_empty() {
        actions.push("nothing to undo".into());
        return Ok(WireReport {
            actions,
            dry_run: dry,
        });
    }
    exim_rebuild(&mut actions, dry);
    Ok(WireReport {
        actions,
        dry_run: dry,
    })
}

/// Fragments present and included.
pub fn installed() -> bool {
    let (r, t) = include_lines();
    router_path().is_file()
        && transport_path().is_file()
        && std::fs::read_to_string(exim_conf_local())
            .is_ok_and(|x| x.contains(&r) && x.contains(&t))
}

// ---- tokens --------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq)]
pub struct Inbox {
    pub token: String,
    pub address: String,
    pub expires: u64,
}

pub fn valid_token(t: &str) -> bool {
    t.len() == 16
        && t.bytes()
            .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit())
}

fn new_token() -> String {
    const ALPHABET: &[u8] = b"abcdefghijklmnopqrstuvwxyz0123456789";
    let mut buf = [0u8; 16];
    let mut ok = false;
    if let Ok(mut f) = std::fs::File::open("/dev/urandom") {
        use std::io::Read;
        ok = f.read_exact(&mut buf).is_ok();
    }
    if !ok {
        let seed = crate::delivery::now_secs() ^ (std::process::id() as u64) << 20;
        for (i, b) in buf.iter_mut().enumerate() {
            *b = ((seed >> (i * 3)) & 0xff) as u8;
        }
    }
    buf.iter()
        .map(|b| ALPHABET[(*b as usize) % ALPHABET.len()] as char)
        .collect()
}

/// A new token, active for `TTL_SECS`.
pub fn create(cfg: &Config) -> std::io::Result<Inbox> {
    let token = new_token();
    let active = spool_dir().join("active");
    std::fs::create_dir_all(&active)?;
    let expires = crate::delivery::now_secs() + TTL_SECS;
    std::fs::write(active.join(format!("dt-{token}")), format!("{expires}\n"))?;
    Ok(Inbox {
        address: format!("dt-{token}@{}", hostname(cfg)),
        token,
        expires,
    })
}

pub fn remove(token: &str) {
    if !valid_token(token) {
        return;
    }
    let _ = std::fs::remove_file(spool_dir().join("active").join(format!("dt-{token}")));
    let _ = std::fs::remove_dir_all(spool_dir().join("box").join(format!("dt-{token}")));
}

#[derive(Debug, Clone)]
pub struct Analysed {
    pub received_at: u64,
    pub from: String,
    pub checks: Vec<Check>,
}

#[derive(Debug, Clone)]
pub struct InboxState {
    pub token: String,
    pub address: String,
    pub expires: u64,
    pub expired: bool,
    /// Still waiting: active and nothing received yet in this poll.
    pub waiting: bool,
    pub messages: Vec<Analysed>,
}

impl InboxState {
    pub fn to_json(&self) -> Json {
        Json::Object(vec![
            ("token".into(), Json::str(&self.token)),
            ("address".into(), Json::str(&self.address)),
            ("expires".into(), Json::Int(self.expires as i64)),
            ("expired".into(), Json::Bool(self.expired)),
            ("waiting".into(), Json::Bool(self.waiting)),
            (
                "messages".into(),
                Json::Array(
                    self.messages
                        .iter()
                        .map(|m| {
                            Json::Object(vec![
                                ("received_at".into(), Json::Int(m.received_at as i64)),
                                ("from".into(), Json::str(&m.from)),
                                (
                                    "checks".into(),
                                    Json::Array(m.checks.iter().map(|c| c.to_json()).collect()),
                                ),
                            ])
                        })
                        .collect(),
                ),
            ),
        ])
    }
}

/// What arrived for `token`: each message is analysed once and then deleted.
pub fn poll(cfg: &Config, token: &str) -> Option<InboxState> {
    if !valid_token(token) {
        return None;
    }
    let active = spool_dir().join("active").join(format!("dt-{token}"));
    let expires: u64 = std::fs::read_to_string(&active)
        .ok()?
        .trim()
        .parse()
        .unwrap_or(0);
    let now = crate::delivery::now_secs();
    let expired = now > expires;
    if expired {
        let _ = std::fs::remove_file(&active);
    }
    let mut messages = Vec::new();
    let boxdir = spool_dir().join("box").join(format!("dt-{token}"));
    let mut files: Vec<PathBuf> = Vec::new();
    for sub in ["new", "cur"] {
        if let Ok(rd) = std::fs::read_dir(boxdir.join(sub)) {
            files.extend(
                rd.filter_map(Result::ok)
                    .map(|e| e.path())
                    .filter(|p| p.is_file()),
            );
        }
    }
    files.sort();
    let dns = crate::dns::Client::system();
    for f in files {
        let received_at = f
            .metadata()
            .and_then(|m| m.modified())
            .ok()
            .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
            .map(|d| d.as_secs())
            .unwrap_or(now);
        let raw = match std::fs::read(&f) {
            Ok(r) if (r.len() as u64) <= MAX_MESSAGE_BYTES => r,
            Ok(_) => {
                let _ = std::fs::remove_file(&f);
                messages.push(Analysed {
                    received_at,
                    from: String::new(),
                    checks: vec![Check::new(
                        "inbox.received",
                        Scope::Receiving,
                        Category::Inbox,
                        Verdict::Unknown,
                        Severity::Info,
                        "a message arrived but is too large to analyse",
                        "over 10 MB",
                    )],
                });
                continue;
            }
            Err(_) => continue,
        };
        let (from, checks) = analyse_inbound(cfg, &dns, &raw, token);
        messages.push(Analysed {
            received_at,
            from,
            checks,
        });
        let _ = std::fs::remove_file(&f);
    }
    Some(InboxState {
        token: token.to_string(),
        address: format!("dt-{token}@{}", hostname(cfg)),
        expires,
        expired,
        waiting: !expired && messages.is_empty(),
        messages,
    })
}

/// The checks for one message that reached the inbox.
pub fn analyse_inbound(
    cfg: &Config,
    dns: &crate::dns::Client,
    raw: &[u8],
    token: &str,
) -> (String, Vec<Check>) {
    use crate::emlcheck::{domain_of, headers_all, parse_mailbox, parse_received};
    let cat = Category::Inbox;
    let sc = Scope::Receiving;
    let (headers, _) = crate::mime::split_headers(raw);
    let from = headers_all(&headers, "from")
        .first()
        .map(|f| parse_mailbox(f).1)
        .unwrap_or_default();
    let rp = headers_all(&headers, "return-path")
        .first()
        .map(|f| parse_mailbox(f).1)
        .unwrap_or_default();
    let mut out = Vec::new();
    // our own hop: the first Received (Exim adds it on arrival)
    let ours = headers_all(&headers, "received")
        .first()
        .map(|r| parse_received(r));
    let client_ip = ours.as_ref().and_then(|r| r.from_ip);
    out.push(
        Check::new(
            "inbox.received",
            sc,
            cat,
            Verdict::Pass,
            Severity::Info,
            format!(
                "message received from {}",
                if from.is_empty() {
                    "an empty From".to_string()
                } else {
                    from.clone()
                }
            ),
            format!(
                "client {}{}",
                client_ip
                    .map(|i| i.to_string())
                    .unwrap_or_else(|| "unknown".into()),
                ours.as_ref()
                    .and_then(|r| r.from.clone())
                    .map(|h| format!(" ({h})"))
                    .unwrap_or_default()
            ),
        )
        .evidence(
            "first Received",
            ours.as_ref().map(|r| r.raw.clone()).unwrap_or_default(),
        ),
    );
    // SPF of the envelope (or From) domain for the client address, as we'd check it
    let no_net = std::env::var_os("MSFE_NG_DELIVERY_NO_NET").is_some();
    let spf_domain = if rp.contains('@') {
        domain_of(&rp)
    } else {
        domain_of(&from)
    };
    match (client_ip, spf_domain.is_empty()) {
        _ if no_net => out.push(Check::new(
            "inbox.spf_here",
            sc,
            cat,
            Verdict::Unknown,
            Severity::Info,
            "SPF",
            "network probes are disabled",
        )),
        (Some(ip), false) if crate::netguard::is_public(ip) => {
            let (r, trace) = crate::spf::evaluate(dns, &spf_domain, ip);
            use crate::spf::SpfResult;
            out.push(match r {
                SpfResult::Pass => Check::new("inbox.spf_here", sc, cat, Verdict::Pass, Severity::Info, format!("SPF pass for {spf_domain} from {ip}"), "the sending server is authorised by the sender domain's SPF").evidence("evaluation", trace.join("\n")),
                SpfResult::Fail | SpfResult::SoftFail => Check::new("inbox.spf_here", sc, cat, Verdict::Fail, Severity::High, format!("SPF {} for {spf_domain} from {ip}", r.as_str()), "the sending server is not in the sender domain's SPF — most receivers junk or reject this").evidence("evaluation", trace.join("\n")).fix_summary(format!("On the sending side: add {ip} to {spf_domain}'s SPF record")),
                SpfResult::None => Check::new("inbox.spf_here", sc, cat, Verdict::Warn, Severity::Medium, format!("{spf_domain} has no SPF record"), "receivers cannot tell whether the server was allowed to send").fix_summary("Publish an SPF record for the sender domain"),
                SpfResult::Neutral => Check::new("inbox.spf_here", sc, cat, Verdict::Warn, Severity::Low, format!("SPF neutral for {spf_domain}"), "the record makes no statement about this server"),
                SpfResult::PermError => Check::new("inbox.spf_here", sc, cat, Verdict::Fail, Severity::Medium, format!("SPF permerror for {spf_domain}"), "the record is broken (too many lookups, syntax)").evidence("evaluation", trace.join("\n")),
                SpfResult::TempError => Check::new("inbox.spf_here", sc, cat, Verdict::Unknown, Severity::Info, "SPF temperror", "DNS did not answer").evidence("evaluation", trace.join("\n")),
            });
        }
        (Some(ip), false) => out.push(Check::new(
            "inbox.spf_here",
            sc,
            cat,
            Verdict::NotApplicable,
            Severity::Info,
            format!("client {ip} is not a public address"),
            "a local submission — SPF does not apply",
        )),
        (None, _) => out.push(Check::new(
            "inbox.spf_here",
            sc,
            cat,
            Verdict::NotApplicable,
            Severity::Info,
            "SPF: local submission",
            "no SMTP client address — the message was handed to Exim on this server",
        )),
        _ => out.push(Check::new(
            "inbox.spf_here",
            sc,
            cat,
            Verdict::Unknown,
            Severity::Info,
            "SPF",
            "no sender domain to evaluate",
        )),
    }
    // DKIM: the signature's key must be published (the signature itself is not verified here)
    if let Some(sig) = headers_all(&headers, "dkim-signature").first() {
        let s = crate::emlcheck::parse_dkim_signature(sig);
        if !s.d.is_empty() && !s.s.is_empty() && !no_net {
            let name = format!("{}._domainkey.{}", s.s, s.d);
            out.push(match dns.txt(&name) {
                Ok(v) if v.iter().any(|t| t.contains("p=")) => {
                    let key = crate::dkim::parse_record(&s.s, v.iter().find(|t| t.contains("p=")).unwrap());
                    if key.revoked {
                        Check::new("inbox.dkim_here", sc, cat, Verdict::Fail, Severity::High, format!("DKIM key {name} is revoked"), "the signature cannot verify: the published key has an empty p=")
                    } else {
                        Check::new("inbox.dkim_here", sc, cat, Verdict::Pass, Severity::Info, format!("DKIM key {name} is published"), format!("{} {} bits — the signature can be verified (this test checks the key, not the cryptography)", key.k, key.bits.map(|b| b.to_string()).unwrap_or_else(|| "?".into())))
                    }
                }
                Ok(_) => Check::new("inbox.dkim_here", sc, cat, Verdict::Fail, Severity::High, format!("no DKIM key at {name}"), "the message is signed with a key nobody can fetch — verification fails, and with DMARC that counts against the sender").fix_summary("On the sending side: publish the selector's public key"),
                Err(e) => Check::new("inbox.dkim_here", sc, cat, Verdict::Unknown, Severity::Info, format!("DKIM key {name}"), format!("could not look up: {e}")),
            });
        }
    } else {
        out.push(Check::new(
            "inbox.dkim_here",
            sc,
            cat,
            Verdict::Warn,
            Severity::Medium,
            "not DKIM-signed",
            "no DKIM-Signature header on arrival",
        ));
    }
    // TLS in, from the Exim log line for the token
    let log_path = PathBuf::from(&cfg.exim_mainlog_path);
    if let Some(text) = crate::cpaudit::tail_bytes(&log_path, 4 * 1024 * 1024) {
        let needle = format!("dt-{token}@");
        if let Some(line) = text
            .lines()
            .rev()
            .find(|l| l.contains(" <= ") && l.to_ascii_lowercase().contains(&needle))
        {
            let l = crate::deliverylog::parse_mainlog_line(line);
            let tls = line
                .split_whitespace()
                .find_map(|t| t.strip_prefix("X="))
                .map(str::to_string);
            let proto = line
                .split_whitespace()
                .find_map(|t| t.strip_prefix("P="))
                .unwrap_or("");
            out.push(match &tls {
                _ if proto == "local" => Check::new("inbox.tls_in", sc, cat, Verdict::NotApplicable, Severity::Info, "submitted locally", "the message was handed to Exim on this server (P=local), not received over SMTP").evidence("exim", line.to_string()),
                Some(x) => Check::new("inbox.tls_in", sc, cat, Verdict::Pass, Severity::Info, "delivered over TLS", format!("{x} ({proto})")).evidence("exim", line.to_string()),
                None => Check::new("inbox.tls_in", sc, cat, Verdict::Warn, Severity::Medium, "delivered in clear text", format!("the sending server did not use STARTTLS ({proto}); the message could be read on the way")).evidence("exim", line.to_string()).fix_summary("On the sending side: enable opportunistic TLS (most MTAs do by default)"),
            });
            if let Some(l) = l {
                if let Some(a) = l.auth {
                    out.push(Check::new(
                        "inbox.auth",
                        sc,
                        cat,
                        Verdict::Pass,
                        Severity::Info,
                        format!("submitted by an authenticated user ({a})"),
                        "the message came from a local account, not from an external server",
                    ));
                }
            }
        }
    }
    // MailScanner / cPanel SpamAssassin verdicts
    let ms_score = headers
        .iter()
        .find(|h| h.to_ascii_lowercase().contains("mailscanner-spamscore:"))
        .and_then(|h| h.split(':').nth(1))
        .map(|v| v.trim().len());
    let ms_check = headers
        .iter()
        .find(|h| h.to_ascii_lowercase().contains("mailscanner-spamcheck:"))
        .and_then(|h| h.split_once(':'))
        .map(|(_, v)| v.trim().to_string());
    let sa_status = headers_all(&headers, "x-spam-status").first().cloned();
    if ms_check.is_some() || sa_status.is_some() {
        let check = ms_check.clone().unwrap_or_default();
        let spam = check.to_ascii_lowercase().starts_with("spam")
            || sa_status
                .as_deref()
                .is_some_and(|s| s.to_ascii_lowercase().starts_with("yes"));
        out.push(if spam {
            Check::new("inbox.mailscanner", sc, cat, Verdict::Warn, Severity::Medium, "flagged as spam on arrival", format!("{}{}", check, sa_status.as_ref().map(|s| format!(" · {s}")).unwrap_or_default())).evidence("headers", headers.iter().filter(|h| h.to_ascii_lowercase().contains("mailscanner") || h.to_ascii_lowercase().starts_with("x-spam")).cloned().collect::<Vec<_>>().join("\n")).fix_summary("The rules named in the verdict say why; if the sender is legitimate, whitelist it or fix the message shape")
        } else {
            Check::new("inbox.mailscanner", sc, cat, Verdict::Pass, Severity::Info, "passed the spam checks on arrival", format!("{}{}", if check.is_empty() { "cPanel SpamAssassin".to_string() } else { check }, ms_score.map(|n| format!(" · score bar {n}")).unwrap_or_default())).evidence("headers", headers.iter().filter(|h| h.to_ascii_lowercase().contains("mailscanner") || h.to_ascii_lowercase().starts_with("x-spam")).cloned().collect::<Vec<_>>().join("\n"))
        });
    } else {
        out.push(Check::new("inbox.mailscanner", sc, cat, Verdict::Unknown, Severity::Info, "no scanner verdict in the headers", "MailScanner or cPanel's SpamAssassin added no headers — the diagnostic address may bypass them, or scanning is off"));
    }
    // the message itself
    let mut eml = crate::emlcheck::analyse_message(raw, &from, None);
    for c in &mut eml {
        c.category = cat;
        c.scope = sc;
    }
    let signed = !headers_all(&headers, "dkim-signature").is_empty();
    out.extend(eml.into_iter().filter(|c| {
        !(c.id == "eml.auth_results" && c.verdict == Verdict::Unknown)
            && c.id != "eml.origin_ip"
            && !(c.id == "eml.dkim_signature" && !signed) // inbox.dkim_here said so
    }));
    (from, out)
}

/// Expired tokens and old boxes go.
pub fn sweep() {
    let now = crate::delivery::now_secs();
    let spool = spool_dir();
    if let Ok(rd) = std::fs::read_dir(spool.join("active")) {
        for e in rd.filter_map(Result::ok) {
            let expires: u64 = std::fs::read_to_string(e.path())
                .ok()
                .and_then(|t| t.trim().parse().ok())
                .unwrap_or(0);
            if now > expires {
                let _ = std::fs::remove_file(e.path());
            }
        }
    }
    if let Ok(rd) = std::fs::read_dir(spool.join("box")) {
        for e in rd.filter_map(Result::ok) {
            use std::os::unix::fs::MetadataExt;
            let old = e
                .metadata()
                .is_ok_and(|m| now.saturating_sub(m.mtime().max(0) as u64) > BOX_KEEP_SECS);
            let name = e.file_name().to_string_lossy().to_string();
            if old && !spool.join("active").join(&name).exists() {
                let _ = std::fs::remove_dir_all(e.path());
            }
        }
    }
}

/// A doctor-style note for the Service tab.
pub fn status_check() -> Check {
    if installed() {
        Check::new(
            "diaginbox",
            Scope::Server,
            Category::Inbox,
            Verdict::Pass,
            Severity::Info,
            "diagnostic inbox installed",
            format!(
                "addresses dt-<token>@<hostname> are routed to {}",
                spool_dir().join("box").display()
            ),
        )
    } else {
        Check::new("diaginbox", Scope::Server, Category::Inbox, Verdict::NotApplicable, Severity::Info, "diagnostic inbox not installed", "the Delivery test tab can give one-time addresses to receive test messages once `msfe-ng delivery inbox install` has wired Exim").fix(Fix {
            summary: "Install the Exim router/transport fragments".into(),
            command: Some("msfe-ng delivery inbox install".into()),
            ..Default::default()
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;

    static ENV: Mutex<()> = Mutex::new(());

    #[test]
    fn splices_include_lines_idempotently() {
        let _g = ENV.lock().unwrap_or_else(|e| e.into_inner());
        std::env::set_var("MSFE_NG_DIAG_CONF_DIR", "/tmp/dc");
        let base =
            "@AUTH@\n\n@PREROUTERS@\n\n@ROUTERSTART@\n\n@TRANSPORTSTART@\n\n@TRANSPORTEND@\n";
        let (once, changed) = splice(base, true);
        assert!(changed);
        assert_eq!(once.matches(START_MARKER).count(), 2);
        assert!(once.contains("@PREROUTERS@\n# --- MSFE-NG diagnostic inbox start ---\n.include_if_exists /tmp/dc/diag-router.conf\n"));
        assert!(once.contains("@TRANSPORTSTART@\n# --- MSFE-NG diagnostic inbox start ---\n.include_if_exists /tmp/dc/diag-transport.conf\n"));
        let (twice, changed2) = splice(&once, true);
        assert!(!changed2);
        assert_eq!(twice, once);
        let (back, changed3) = splice(&once, false);
        assert!(changed3);
        assert_eq!(back, base);
        // missing markers are appended
        let (added, _) = splice("@AUTH@\n", true);
        assert!(added.contains("\n@PREROUTERS@\n"));
        assert!(added.contains("\n@TRANSPORTSTART@\n"));
        std::env::remove_var("MSFE_NG_DIAG_CONF_DIR");
    }

    #[test]
    fn wire_unwire_and_poll_over_fixtures() {
        let _g = ENV.lock().unwrap_or_else(|e| e.into_inner());
        let root = std::env::temp_dir().join(format!("msfe-diag-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).unwrap();
        std::fs::write(
            root.join("exim.conf.local"),
            "@PREROUTERS@\n\n@TRANSPORTSTART@\n",
        )
        .unwrap();
        std::env::set_var("MSFE_NG_EXIM_CONF_LOCAL", root.join("exim.conf.local"));
        std::env::set_var("MSFE_NG_DIAG_CONF_DIR", root.join("etc"));
        std::env::set_var("MSFE_NG_DIAG_SPOOL", root.join("spool"));
        std::env::set_var("MSFE_NG_DIAG_HOSTNAME", "host.test");
        std::env::set_var("MSFE_NG_SKIP_EXIM_CMDS", "1");
        let cfg = Config::default();
        assert!(!installed());
        let r = wire(&cfg, true).unwrap();
        assert!(r.dry_run && !installed());
        let r = wire(&cfg, false).unwrap();
        assert!(r.actions.iter().any(|a| a.starts_with("wrote")));
        assert!(installed());
        assert!(router_fragment().contains("local_parts = \\N^dt-[a-z0-9]{16}$\\N"));
        assert!(std::fs::read_to_string(root.join("etc/diag-router.conf"))
            .unwrap()
            .contains(&format!(
                "dsearch{{{}/active}}",
                root.join("spool").display()
            )));
        // second wire: nothing to change in exim.conf.local
        let r = wire(&cfg, false).unwrap();
        assert!(r.actions.iter().any(|a| a.contains("already has")));
        // a token, a message, a poll
        let inbox = create(&cfg).unwrap();
        assert!(valid_token(&inbox.token));
        assert_eq!(inbox.address, format!("dt-{}@host.test", inbox.token));
        let st = poll(&cfg, &inbox.token).unwrap();
        assert!(st.waiting && st.messages.is_empty());
        let newdir = root
            .join("spool/box")
            .join(format!("dt-{}", inbox.token))
            .join("new");
        std::fs::create_dir_all(&newdir).unwrap();
        std::fs::write(newdir.join("1.msg"), "Received: from mail.sender.test ([185.199.108.25]) by host.test with esmtps id x; Sat, 19 Sep 2026 10:00:00 +0000\r\nFrom: someone@sender.test\r\nTo: dt-x@host.test\r\nSubject: test\r\nDate: Sat, 19 Sep 2026 09:59:00 +0000\r\nMessage-ID: <1@sender.test>\r\nX-host.test-MailScanner-SpamCheck: not spam, SpamAssassin (score=0.1)\r\n\r\nhello\r\n").unwrap();
        std::env::set_var("MSFE_NG_DELIVERY_NO_NET", "1");
        std::env::set_var("MSFE_NG_RESOLVER", "127.0.0.1:1");
        let st = poll(&cfg, &inbox.token).unwrap();
        std::env::remove_var("MSFE_NG_RESOLVER");
        std::env::remove_var("MSFE_NG_DELIVERY_NO_NET");
        assert_eq!(st.messages.len(), 1);
        assert_eq!(st.messages[0].from, "someone@sender.test");
        let ids: Vec<&str> = st.messages[0]
            .checks
            .iter()
            .map(|c| c.id.as_str())
            .collect();
        assert!(
            ids.contains(&"inbox.received")
                && ids.contains(&"inbox.mailscanner")
                && ids.contains(&"eml.headers.required"),
            "{ids:?}"
        );
        assert!(st.messages[0]
            .checks
            .iter()
            .all(|c| c.category == Category::Inbox));
        assert!(
            !newdir.join("1.msg").exists(),
            "analysed messages are deleted"
        );
        // gone after removal
        remove(&inbox.token);
        assert!(poll(&cfg, &inbox.token).is_none());
        let r = unwire(false).unwrap();
        assert!(r.actions.iter().any(|a| a.starts_with("removed")));
        assert!(!installed());
        assert_eq!(
            std::fs::read_to_string(root.join("exim.conf.local")).unwrap(),
            "@PREROUTERS@\n\n@TRANSPORTSTART@\n"
        );
        for v in [
            "MSFE_NG_EXIM_CONF_LOCAL",
            "MSFE_NG_DIAG_CONF_DIR",
            "MSFE_NG_DIAG_SPOOL",
            "MSFE_NG_DIAG_HOSTNAME",
            "MSFE_NG_SKIP_EXIM_CMDS",
        ] {
            std::env::remove_var(v);
        }
        let _ = std::fs::remove_dir_all(&root);
    }
}
