//! SpamBox Exim fragment generation.
//!
//! "SpamBox" delivers messages MailScanner tagged with `X-MailScanner-SpamBox: yes`
//! into the recipient's spam folder instead of the inbox. MailScanner adds the
//! header (via the spam action `deliver header "X-MailScanner-SpamBox: yes"`);
//! this Exim fragment acts on it at delivery time.
//!
//! We generate a self-contained fragment delimited by markers and write it to a
//! standalone file that the operator (or the Exim hook) `.include_if_exists`-es.
//! MSFE-NG never edits `exim.conf` directly. Clean-room: modeled on the observed
//! behavior of the original `spambox.conf`, written fresh.

pub const START_MARKER: &str = "# --- MSFE-NG SpamBox start ---";
pub const END_MARKER: &str = "# --- MSFE-NG SpamBox end ---";

/// The Exim router+transport fragment. Idempotent to write; safe to remove.
pub fn fragment() -> String {
    format!(
        "{START_MARKER}
# Delivers X-MailScanner-SpamBox tagged mail to the recipient's spam folder.
# Generated by `msfe-ng spambox enable`. Do not edit between the markers.
msfe_ng_spambox_router:
  driver = accept
  condition = ${{if eq{{$h_X-MailScanner-SpamBox:}}{{yes}}}}
  transport = msfe_ng_spambox_transport
  # only act for local recipients handled by the local delivery flow
  domains = +local_domains

msfe_ng_spambox_transport:
  driver = appendfile
  maildir_format
  directory = $home/mail/${{quote_local_part:$domain}}/.spam
  create_directory
  directory_mode = 0700
  mode = 0600
  user = $local_part
{END_MARKER}
"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fragment_has_markers_and_header_check() {
        let f = fragment();
        assert!(f.starts_with(START_MARKER));
        assert!(f.trim_end().ends_with(END_MARKER));
        assert!(f.contains("X-MailScanner-SpamBox:"));
        assert!(f.contains("msfe_ng_spambox_router"));
    }
}
