name=msfe_ng
id=msfe_ng
version=0.0.1
author=Martini Multimedia s.a.s.
author_url=https://github.com/inalto/msfe-ng
date=2026-07-20
active=yes
description=MSFE-NG — open-source MailScanner Front-End
# Show in the admin and user levels; reseller inherits admin.
admin_menu=1
user_menu=1
admin_name=MSFE-NG MailScanner
user_name=MailScanner Settings
